### ISSUE TITLE
Wrong builddir behavior

### ISSUE THREAD

**Issue by kergoth** [garmin/pyrex#32]
After working around #31:
```
$ pwd
/data/kergoth/mel/yocto-test/pyrex-test
$ PYREX_OEROOT=$PWD/oe-core PYREX_OEINIT=$PWD/oe-core/oe-init-build-env . ./pyrex/pyrex-init-build-env

### Shell environment set up for builds. ###

You can now run 'bitbake <target>'

Common targets are:
    core-image-minimal
    core-image-sato
    meta-toolchain
    meta-ide-support

You can also run generated qemu images with a command like 'runqemu qemux86'.

Other commonly useful commands are:
 - 'devtool' and 'recipetool' handle common recipe tasks
 - 'bitbake-layers' handles common layer tasks
 - 'oe-pkgdata-util' handles common target package tasks
$ pwd
/data/kergoth/mel/yocto-test/pyrex-test/build
$ which bitbake
bitbake is /data/kergoth/mel/yocto-test/pyrex-test/build/pyrex/bin/bitbake
$ bitbake -e | grep TOPDIR=
TOPDIR="/data/kergoth/mel/yocto-test/pyrex-test/oe-core/build"
$
```

Investigating further.

**Comment by kergoth** [comment]
It looks like there's a problem with relative paths. `. ./pyrex/pyrex-init-build-env build bitbake` results in `Error: The bitbake directory (/data/kergoth/mel/yocto-test/pyrex-test/oe-core/bitbake) does not exist!  Please ensure a copy of bitbake exists at this location or specify an alternative path on the command line`, even though the source was done while in pyrex-test, not oe-core, and pyrex-test/bitbake exists. It's resolving the relative paths from oe-core, not $PWD.

**Comment by kergoth** [comment]
It also forcibly unsets PYREX_OEROOT PYREX_OEINIT PYREX_ROOT in cleanup, even if I set those myself, pyrex-init-build-env didn't do it, so I have to keep re-setting them myself, but that's a different bug.

**Comment by kergoth** [comment]
> 
> 
> It looks like this is a problem with relative paths. `. ./pyrex/pyrex-init-build-env build bitbake` results in `Error: The bitbake directory (/data/kergoth/mel/yocto-test/pyrex-test/oe-core/bitbake) does not exist! Please ensure a copy of bitbake exists at this location or specify an alternative path on the command line`, even though the source was done while in pyrex-test, not oe-core, and pyrex-test/bitbake exists. It's resolving the relative paths from oe-core, not $PWD.

This issue seems to have its root in startup.sh:
```
if [ -n "$PYREX_OEROOT" ] && [ -n "$PYREX_INIT_COMMAND" ]; then
    pushd "$PYREX_OEROOT" > /dev/null
    source $PYREX_INIT_COMMAND > /dev/null
    popd > /dev/null
fi
```

It sources the init command in docker context from oeroot, not pwd, even though it was sourced from pwd outside of docker, so the context isn't the same, which breaks when relative paths are involved. Presumably this was to ensure things don't break if INIT_COMMAND itself is relative, but that could be addressed elsewhere.

**Comment by kergoth** [comment]
I don't see a clean way to handle this unless init_command also includes the original pwd from when pyrex-init-build-env is sourced in some fashion, as sourcing PYREX_INIT_COMMAND from $PWD at bitbake-execution time will be wrong too, and we can't make assumptions about the semantics of the OEINIT command other than that we source it and pass args through.

**Comment by kergoth** [comment]
https://github.com/garmin/pyrex/compare/master...kergoth:master seems to get past this issue.

**Comment by JoshuaWatt** [comment]
Just so I understand the problem better: In your very first example, what would the expected output of `bitbake -e | grep TOPDIR=` be? I'm guessing:
```
$ bitbake -e | grep TOPDIR=
/data/kergoth/mel/yocto-test/pyrex-test/build
```

**Comment by JoshuaWatt** [comment]
Ok, I've been trying to write a test case that exercises this, and I think I've got one that works reasonably well (although there are still a few kinks to work out). Unfortunately, it looks like this fix doesn't actually fix the behavior my test case is exposing (assuming my test case is actually testing the correct thing):

Would you mind taking a look at: 
https://github.com/JoshuaWatt/pyrex/commit/e87ee56ecc615d7d3a3102743344126891b94826 ?

**Comment by kergoth** [comment]
> 
> 
> Just so I understand the problem better: In your very first example, what would the expected output of `bitbake -e | grep TOPDIR=` be? I'm guessing:
> 
> ```
> $ bitbake -e | grep TOPDIR=
> /data/kergoth/mel/yocto-test/pyrex-test/build
> ```

Yes, if pwd and TOPDIR don't match, then I think I'm working in one build dir when I'm actually working in another. conf/bblayers.conf doesn't match what's being used, etc. Very confusing. The current code only works properly if you always create your build directories inside of COREBASE, but that's not always the case, particularly for non-poky environments.

**Comment by JoshuaWatt** [comment]
Ah, OK. I figured out the problem. The issue was entirely with my tests setup not your patch. I've correctly written a test that will exposes this issue, and verified that you patch fixes it. I have some small cleanup I would like done on the patch (I'll leave comments in the PR), but otherwise it looks good. Thanks!
