### ISSUE TITLE
Add PYREX_USER to Docker Group if it exists.

### ISSUE THREAD

**Issue by jamesharris-garmin** [garmin/pyrex#42]
In some images based on pyrex we will want to add our `PYREX_USER` to the `docker` group if that group is already created. This will allow us to access the docker daemon without the need to use sudo locally.

**Comment by JoshuaWatt** [comment]
I'm going to close this issue as inappropriate. Accessing the docker itself from inside pyrex is beyond the scope of the project

**Comment by jamesharris-garmin** [comment]
no objections from me. this wouldn't make sense in podman anyway.
